"""Update About model - add title, is_active, display_order fields

Revision ID: 4ca431a4a006
Revises: f9db621d8096
Create Date: 2025-11-04 22:25:20.607526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca431a4a006'
down_revision = 'f9db621d8096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    from sqlalchemy.engine import reflection
    
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('about')]
    
    # 先添加可空字段（如果不存在）
    with op.batch_alter_table('about', schema=None) as batch_op:
        if 'title' not in columns:
            batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        if 'is_active' not in columns:
            batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        if 'display_order' not in columns:
            batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))
        if 'created_at' not in columns:
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # 为现有数据填充默认值
    op.execute("UPDATE about SET title = '關於我們' WHERE title IS NULL OR title = ''")
    op.execute("UPDATE about SET is_active = 1 WHERE is_active IS NULL")
    op.execute("UPDATE about SET display_order = 1 WHERE display_order IS NULL")
    op.execute("UPDATE about SET created_at = NOW() WHERE created_at IS NULL")
    
    # 改为不可空并创建索引
    indexes = [idx['name'] for idx in inspector.get_indexes('about')]
    
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.alter_column('title', 
                            existing_type=sa.String(length=200),
                            nullable=False)
        batch_op.alter_column('is_active',
                            existing_type=sa.Boolean(),
                            nullable=False)
        batch_op.alter_column('display_order',
                            existing_type=sa.Integer(),
                            nullable=False)
        batch_op.alter_column('created_at',
                            existing_type=sa.DateTime(),
                            nullable=False)
        
        if 'idx_about_active' not in indexes:
        batch_op.create_index('idx_about_active', ['is_active'], unique=False)
        if 'idx_about_order' not in indexes:
        batch_op.create_index('idx_about_order', ['display_order'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.drop_index('idx_about_order')
        batch_op.drop_index('idx_about_active')
        batch_op.drop_column('created_at')
        batch_op.drop_column('display_order')
        batch_op.drop_column('is_active')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
