"""Add recipient and payment fields to Order model

Revision ID: 61192542e871
Revises: 5b2c3d4e5f6a
Create Date: 2025-11-05 09:50:24.595389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61192542e871'
down_revision = '5b2c3d4e5f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('recipient_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('recipient_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('delivery_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('delivery_note')
        batch_op.drop_column('recipient_address')
        batch_op.drop_column('recipient_phone')
        batch_op.drop_column('recipient_name')

    # ### end Alembic commands ###
