"""add_shop_order_id_to_shop

Revision ID: 66628b571df0
Revises: 8668db9120be
Create Date: 2025-11-05 12:16:04.904136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66628b571df0'
down_revision = '8668db9120be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_order_id', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_shop_shop_order_id'), ['shop_order_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_shop_order_id'))
        batch_op.drop_column('shop_order_id')

    # ### end Alembic commands ###
