"""add_order_number_and_system_settings

Revision ID: 8668db9120be
Revises: 61192542e871
Create Date: 2025-11-05 11:52:36.599560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8668db9120be'
down_revision = '61192542e871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    
    # 检查 system_setting 表是否存在
    if 'system_setting' not in inspector.get_table_names():
        op.create_table('system_setting',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('setting_key', sa.String(length=100), nullable=False),
        sa.Column('setting_value', sa.Text(), nullable=True),
        sa.Column('setting_type', sa.String(length=20), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('is_encrypted', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        
        # 创建索引
        with op.batch_alter_table('system_setting', schema=None) as batch_op:
            batch_op.create_index('idx_setting_category', ['category'], unique=False)
            batch_op.create_index(batch_op.f('ix_system_setting_setting_key'), ['setting_key'], unique=True)

    # 检查 order 表是否已有 order_number 字段
    order_columns = [col['name'] for col in inspector.get_columns('order')]
    
    # 添加 order_number 字段（先设为 nullable）
    if 'order_number' not in order_columns:
        with op.batch_alter_table('order', schema=None) as batch_op:
            batch_op.add_column(sa.Column('order_number', sa.String(length=50), nullable=True))
    
    # 为已存在的订单生成编号
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id, shop_id, created_at FROM `order` WHERE order_number IS NULL ORDER BY created_at"))
    
    for row in result:
        order_id = row[0]
        shop_id = row[1]
        created_at = row[2]
        
        # 获取商店编码
        shop_result = connection.execute(sa.text(f"SELECT id FROM shop WHERE id = {shop_id}"))
        shop_row = shop_result.fetchone()
        if shop_row:
            shop_code = f"SHOP{str(shop_id).zfill(2)}"
            date_str = created_at.strftime('%Y%m%d')
            
            # 获取当天该店铺的订单数量
            count_result = connection.execute(sa.text(
                f"SELECT COUNT(*) FROM `order` WHERE shop_id = {shop_id} "
                f"AND DATE(created_at) = DATE('{created_at.strftime('%Y-%m-%d')}') "
                f"AND id <= {order_id}"
            ))
            count = count_result.scalar()
            sequence = str(count).zfill(4)
            
            order_number = f"ORDER{shop_code}{date_str}{sequence}"
            
            # 更新订单编号
            connection.execute(sa.text(
                f"UPDATE `order` SET order_number = '{order_number}' WHERE id = {order_id}"
            ))
    
    # 将 order_number 改为 not null 并创建索引
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_number', 
                            existing_type=sa.String(length=50),
                            nullable=False)
        batch_op.create_index(batch_op.f('ix_order_order_number'), ['order_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_order_number'))
        batch_op.drop_column('order_number')

    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_setting_setting_key'))
        batch_op.drop_index('idx_setting_category')

    op.drop_table('system_setting')
    # ### end Alembic commands ###
