"""add_soft_delete_fields_to_shop_and_product

Revision ID: bf3e210941aa
Revises: e716eac430e9
Create Date: 2025-11-05 15:41:59.079472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3e210941aa'
down_revision = 'e716eac430e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_shop_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shop_deleted_at'))
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_deleted_at'))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
