"""add_drink_options_to_product_and_order_item

Revision ID: e716eac430e9
Revises: 53a409aac578
Create Date: 2025-11-05 15:17:13.042495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e716eac430e9'
down_revision = '53a409aac578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drink_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('drink_price', sa.Numeric(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        # 先添加為 nullable，避免现有记录出错
        batch_op.add_column(sa.Column('has_cold_drink', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cold_drink_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('has_hot_drink', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hot_drink_price', sa.Numeric(precision=10, scale=2), nullable=True))
    
    # 更新現有記錄的默認值
    op.execute("UPDATE product SET has_cold_drink = 0 WHERE has_cold_drink IS NULL")
    op.execute("UPDATE product SET has_hot_drink = 0 WHERE has_hot_drink IS NULL")
    
    # 然後改為 NOT NULL
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('has_cold_drink', existing_type=sa.Boolean(), nullable=False)
        batch_op.alter_column('has_hot_drink', existing_type=sa.Boolean(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('hot_drink_price')
        batch_op.drop_column('has_hot_drink')
        batch_op.drop_column('cold_drink_price')
        batch_op.drop_column('has_cold_drink')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('drink_price')
        batch_op.drop_column('drink_type')

    # ### end Alembic commands ###
