"""Add title, subtitle, link to HomeBanner

Revision ID: f90d1ba6435a
Revises: 
Create Date: 2025-11-04 21:16:48.285007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90d1ba6435a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_banner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('subtitle', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_banner', schema=None) as batch_op:
        batch_op.drop_column('link')
        batch_op.drop_column('subtitle')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
